import type { ColorDefinition } from "@/types/colors";

export const colorsAtelierAnimation = {
    encre: {
        label: "Encre",
        token: "--atelier-animation-encre",
        value: "#15171D",
        cssValue: "var(--atelier-animation-encre)",
        foreground: "light",
    },
    "table-lumineuse": {
        label: "Table lumineuse",
        token: "--atelier-animation-table-lumineuse",
        value: "#252A32",
        cssValue: "var(--atelier-animation-table-lumineuse)",
        foreground: "light",
    },
    graphite: {
        label: "Graphite",
        token: "--atelier-animation-graphite",
        value: "#88838C",
        cssValue: "var(--atelier-animation-graphite)",
        foreground: "dark",
    },
    "papier-animation": {
        label: "Papier animation",
        token: "--atelier-animation-papier-animation",
        value: "#F1E7D2",
        cssValue: "var(--atelier-animation-papier-animation)",
        foreground: "dark",
    },
    "rouge-crayon": {
        label: "Rouge crayon",
        token: "--atelier-animation-rouge-crayon",
        value: "#C06464",
        cssValue: "var(--atelier-animation-rouge-crayon)",
        foreground: "dark",
    },
    "corail-cel": {
        label: "Corail cel",
        token: "--atelier-animation-corail-cel",
        value: "#C5785C",
        cssValue: "var(--atelier-animation-corail-cel)",
        foreground: "dark",
    },
    "sepia-storyboard": {
        label: "Sépia storyboard",
        token: "--atelier-animation-sepia-storyboard",
        value: "#9A735D",
        cssValue: "var(--atelier-animation-sepia-storyboard)",
        foreground: "dark",
    },
    "orange-banc-titre": {
        label: "Orange banc-titre",
        token: "--atelier-animation-orange-banc-titre",
        value: "#C88952",
        cssValue: "var(--atelier-animation-orange-banc-titre)",
        foreground: "dark",
    },
    "ambre-projecteur": {
        label: "Ambre projecteur",
        token: "--atelier-animation-ambre-projecteur",
        value: "#B98745",
        cssValue: "var(--atelier-animation-ambre-projecteur)",
        foreground: "dark",
    },
    "jaune-lampe": {
        label: "Jaune lampe",
        token: "--atelier-animation-jaune-lampe",
        value: "#D3AC55",
        cssValue: "var(--atelier-animation-jaune-lampe)",
        foreground: "dark",
    },
    "olive-decor": {
        label: "Olive décor",
        token: "--atelier-animation-olive-decor",
        value: "#89945F",
        cssValue: "var(--atelier-animation-olive-decor)",
        foreground: "dark",
    },
    "vert-cellulo": {
        label: "Vert cellulo",
        token: "--atelier-animation-vert-cellulo",
        value: "#6E9A87",
        cssValue: "var(--atelier-animation-vert-cellulo)",
        foreground: "dark",
    },
    "turquoise-acetate": {
        label: "Turquoise acétate",
        token: "--atelier-animation-turquoise-acetate",
        value: "#57959A",
        cssValue: "var(--atelier-animation-turquoise-acetate)",
        foreground: "dark",
    },
    "cyan-effets-optiques": {
        label: "Cyan effets optiques",
        token: "--atelier-animation-cyan-effets-optiques",
        value: "#62A4B2",
        cssValue: "var(--atelier-animation-cyan-effets-optiques)",
        foreground: "dark",
    },
    "bleu-reperage": {
        label: "Bleu repérage",
        token: "--atelier-animation-bleu-reperage",
        value: "#5E88AD",
        cssValue: "var(--atelier-animation-bleu-reperage)",
        foreground: "dark",
    },
    "indigo-nuit-studio": {
        label: "Indigo nuit studio",
        token: "--atelier-animation-indigo-nuit-studio",
        value: "#6875A4",
        cssValue: "var(--atelier-animation-indigo-nuit-studio)",
        foreground: "dark",
    },
    "violet-ombre-portee": {
        label: "Violet ombre portée",
        token: "--atelier-animation-violet-ombre-portee",
        value: "#78658F",
        cssValue: "var(--atelier-animation-violet-ombre-portee)",
        foreground: "light",
    },
    gouache: {
        label: "Gouache",
        token: "--atelier-animation-gouache",
        value: "#9172A7",
        cssValue: "var(--atelier-animation-gouache)",
        foreground: "dark",
    },
    "rose-aerographe": {
        label: "Rose aérographe",
        token: "--atelier-animation-rose-aerographe",
        value: "#B87591",
        cssValue: "var(--atelier-animation-rose-aerographe)",
        foreground: "dark",
    },
    "framboise-encrage": {
        label: "Framboise encrage",
        token: "--atelier-animation-framboise-encrage",
        value: "#AA6077",
        cssValue: "var(--atelier-animation-framboise-encrage)",
        foreground: "dark",
    },
} as const satisfies Record<string, ColorDefinition>;
